name: 'Your name here'
description: 'Provide a description here'
author: 'Your name or organization here'
inputs:
  branch:
    required: true
    description: 'the branch name to be saved to the API'
runs:
  using: 'node16'
  main: 'dist/index.js'
